# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Python_Projects\PyQt5 Progress Bar\imgtotext.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from actions import Main
import PIL
from cv import *

def back(mw):
    mw.close()
    os.system("mmenu.exe")
def save_ascii_art(main_widget, img_path_input):
    
    saved_file = Main.save_file_and_get_path(main_widget)
    if saved_file.strip()!="" and saved_file!=None and os.path.exists(img_path_input.text()):
        try:
            image_to_ascii_art(img_path_input.text(),saved_file)
        except PIL.UnidentifiedImageError:
            alert("Selected File is not an Image File!, Please Select an Image File",Styles.Icons.ICON_ERROR,"SIMx67889")
        except:
            alert("Sorry! Some unknown Error occured",Styles.Icons.ICON_ERROR,"UKNx124452")        
    else:
        alert("Could not save ascii art!, Incorrect Path",Styles.Icons.ICON_ERROR,"CSAx82234")    

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(10, 0, 781, 101))
        self.Title.setObjectName("Title")
        self.img_path_label = QtWidgets.QLabel(self.centralwidget)
        self.img_path_label.setGeometry(QtCore.QRect(20, 130, 121, 31))
        self.img_path_label.setObjectName("img_path_label")
        self.image_path_input = QtWidgets.QLineEdit(self.centralwidget)
        self.image_path_input.setGeometry(QtCore.QRect(140, 130, 181, 31))
        self.image_path_input.setObjectName("image_path_input")
        self.convert_btn = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:save_ascii_art(self.centralwidget,self.image_path_input))
        self.convert_btn.setGeometry(QtCore.QRect(110, 200, 221, 41))
        self.convert_btn.setObjectName("convert_btn")
        self.convert_btn_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:Main.open_file(self=self,img_inp=self.image_path_input))
        self.convert_btn_2.setGeometry(QtCore.QRect(330, 130, 71, 31))
        self.convert_btn_2.setObjectName("convert_btn_2")
        self.convert_btn_4 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:back(MainWindow))
        self.convert_btn_4.setGeometry(QtCore.QRect(110, 280, 221, 41))
        self.convert_btn_4.setObjectName("convert_btn_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Image to Text Art Converter</span></p></body></html>"))
        self.img_path_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Image Path:</span></p></body></html>"))
        self.convert_btn.setText(_translate("MainWindow", "Save Text Art"))
        self.convert_btn_2.setText(_translate("MainWindow", "Browse"))
        self.convert_btn_4.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
